spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: Colin0611/
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

